// Generated by CoffeeScript 1.8.0
(function() {
  var logger, start;

  logger = require("./modules/logger.js");

  logger.guardStart();

  start = function() {
    var ls;
    ls = require("child_process").spawn("node", ["modules/http.js"]);
    ls.stdout.pipe(process.stdout);
    ls.stderr.on("data", function(data) {
      return logger.guardError(data);
    });
    ls.on("exit", function(code) {
      logger.guardRestart(code);
      return setTimeout(start, 2000);
    });
    return logger.guardReady();
  };

  start();

}).call(this);

//# sourceMappingURL=app.js.map
