#!/bin/bash

DIR=/data/www/AuthTHU
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node
PID_PATH=/var/run

test -x $NODE || exit 0

function start_app {
  echo "Starting AuthTHU Server"
  cd "$DIR"
  NODE_ENV=production nohup "$NODE" "app.js" 1>>"log" 2>&1 &
  echo $! > "$PID_PATH/AuthTHU.pid"
}

function stop_app {
  echo "Stopping AuthTHU Server"
  kill `cat $PID_PATH/AuthTHU.pid 2>/dev/null` 2>/dev/null
}

case $1 in
   start)
      stop_app
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: AuthTHU {start|stop}" ;;
esac
exit 0
